"""add

Revision ID: 24f119636b55
Revises: 07611ecef869
Create Date: 2023-09-25 12:19:48.092175

"""
import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24f119636b55'
down_revision = '07611ecef869'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_role', sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_role', 'id')
    # ### end Alembic commands ###
