"""add

Revision ID: d0c236950ea8
Revises: 24f119636b55
Create Date: 2023-09-25 12:36:01.255994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0c236950ea8'
down_revision = '24f119636b55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_role', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_role', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
